# Site Settings
title: "Sky Kehan Sheng "
description: "AI Bias Researcher | Data Scientist <br> AI Applications for Animal Welfare | PhD Candidate, UBC" 
url: "https://skysheng7.github.io"
repository: "skysheng7/skysheng7.github.io"

# Site Author
author:
  name: "Sky (Kehan) Sheng"
  bio: "Data Scientist & AI Bias Researcher passionate about using AI to empower marginalized communities and address real-world challenges"
  location: "Vancouver, BC, Canada"
  email: "skysheng7@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/skysheng7"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sky-sheng"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=yz-cWVgAAAAJ"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0001-6442-5284"

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  research:
    output: true
    permalink: /:collection/:name/
  projects:
    output: true
    permalink: /:collection/:name/
  talks:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Vancouver

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# SEO
google_site_verification: googlee57ba1f04e0cb377.html
lang: en_US

# Include files
include:
  - "*.pdf"
  - "Sky_CV.pdf"

# Keep files
keep_files:
  - "*.pdf"
  - "Sky_CV.pdf"

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development 